import type { Metadata } from "next";
import Posts from "@/components/Posts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <Posts />
    </main>
  );
}
